#ifndef SPLITS_TO_ELEMENTS_H
#define SPLITS_TO_ELEMENTS_H

/* this is a preprocessing function for
 * refine_topology.
 * the entity type which is being split
 * is referred to as the source (src) type,
 * and information about about the
 * generation (gen) of new entities is processed.
 * in particular, given the
 * element to source downward adjacency graph,
 * the offsets describing which sources will split,
 * and a map from sources to generated vertices,
 * this function computes for the elements:
 * offsets describing which elements will split,
 * the relative direction from an element to its source,
 * and the vertex generated by the element's source
 *
 * this assumes that each element is adjacent to
 * at most one source
 */

void project_splits_to_elements(
    unsigned elem_dim,
    unsigned src_dim,
    unsigned nelems,
    unsigned const* srcs_of_elems,
    unsigned const* gen_offset_of_srcs,
    unsigned const* gen_vert_of_srcs,
    unsigned** gen_offset_of_elems_out,
    unsigned** gen_direction_of_elems_out,
    unsigned** gen_vert_of_elems_out);

struct mesh;

void mesh_splits_to_elements(
  struct mesh* m,
  unsigned src_dim,
  unsigned const* gen_offset_of_srcs,
  unsigned const* gen_vert_of_srcs,
  unsigned** p_gen_offset_of_elems,
  unsigned** p_gen_direction_of_elems,
  unsigned** p_gen_vert_of_elems);

#endif
