.TH osh_components 3 "2/16/2016" " " ""
.SH NAME
osh_components \-  Get the number of components of a field or label. 
.SH SYNOPSIS
.nf
unsigned osh_components(osh_t m, unsigned dim, char const* name)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B m 
- mesh handle
.PD 1
.PD 0
.TP
.B dim 
- the dimension of entities
.PD 1
.PD 0
.TP
.B name 
- the field or label name
.PD 1

Level: intermediate

.SH SEE ALSO
osh_nfields()
.br
