.TH osh_free_label 3 "4/19/2016" " " ""
.SH NAME
osh_free_label \-  Destroy a label. 
.SH SYNOPSIS
.nf
void osh_free_label(osh_t m, unsigned dim, char const* name)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B m 
- mesh handle
.PD 1
.PD 0
.TP
.B dim 
- the entity dimension over which the label is defined
.PD 1
.PD 0
.TP
.B name 
- the label name
.PD 1

Level: beginner

.SH SEE ALSO
osh_new_label()
.br
