.TH osh_get_label 3 "2/16/2016" " " ""
.SH NAME
osh_get_label \-  Access data for a label. 
.SH SYNOPSIS
.nf
unsigned* osh_get_label(osh_t m, unsigned dim, char const* name)
.fi
Returns the internal data array of a label.

In CUDA mode, the array is in device memory.

.SH INPUT PARAMETERS
.PD 0
.TP
.B m 
- mesh handle
.PD 1
.PD 0
.TP
.B dim 
- the dimension of entities
.PD 1
.PD 0
.TP
.B name 
- the label name
.PD 1

Level: beginner

.SH SEE ALSO
osh_new_label()
.br
