.TH osh_own_rank 3 "2/16/2016" " " ""
.SH NAME
osh_own_rank \-  Get the owning MPI ranks of entities. 
.SH SYNOPSIS
.nf
unsigned const* osh_own_rank(osh_t m, unsigned dim)
.fi
Returns a read-only array containing the owner
MPI rank for each entity of a given dimension.
This ownership is often determined by omega_h
and affects the behavior of osh_accumulate_to_owner()
and osh_conform().

In CUDA mode, the array is in device memory.

.SH INPUT PARAMETERS
.PD 0
.TP
.B m 
- mesh handle
.PD 1
.PD 0
.TP
.B dim 
- the dimension of entities to inquire about
.PD 1

Level: intermediate

.SH SEE ALSO
osh_own_id(), osh_accumulate_to_owner(), osh_conform(), osh_global()
.br
