.TH osh_count 3 "2/16/2016" " " ""
.SH NAME
osh_count \-  Get the number of mesh entities of one dimension 
.SH SYNOPSIS
.nf
unsigned osh_count(osh_t m, unsigned dim)
.fi
Returns the number of entities of the given
dimension on this MPI rank.

.SH INPUT PARAMETERS
.PD 0
.TP
.B m 
- mesh handle
.PD 1

Level: beginner

.SH SEE ALSO
osh_count()
.br
